CREATE DATABASE STUDENT_PORTFOLIO_DATABASE;
USE STUDENT_PORTFOLIO_DATABASE;
CREATE TABLE STUDENT_DETAILS (
  ID INT PRIMARY KEY,
  NAME VARCHAR(20),
  AGE INT,
  PHONENO BIGINT UNIQUE,
  EMAILID VARCHAR(30),
  ADDRESS VARCHAR(100),
  GITHUBLINK VARCHAR(50),
  LINKEDINLINK VARCHAR(50),
  HACKERRANK VARCHAR(50)
);
DESCRIBE STUDENT_DETAILS;
DROP TABLE STUDENT_DETAILS;